name: dartfn_server
description: A sample "Hello, World!" Functions Framework project.
# version: 0.1.0
# homepage: https://www.example.com
publish_to: none

environment:
  sdk: ">=2.10.5 <3.0.0"

dependencies:
  functions_framework: ^0.3.1
  shelf: ^0.7.9
  cron: ^0.2.4

dev_dependencies:
  build_runner: ^1.10.7
  functions_framework_builder: ^0.3.1
  http: ^0.12.2
  test: ^1.15.7
